controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /api/auth
    methods: ['POST']

# Route pour afficher la liste des sociétés auxquelles appartient l'utilisateur
user_companies:
    path: /companies
    controller: App\Controller\CompanyController::getUserCompanies
    methods: ['GET']

# Route pour afficher les détails d'une société
company_details:
    path: /companies/{id}
    controller: App\Controller\CompanyController::getCompanyDetails
    methods: ['GET']

# Route pour créer un projet
create_project:
    path: /companies/{companyId}/projects/new
    controller: App\Controller\ProjectController::createProject
    methods: ['GET', 'POST']

# Route pour afficher les projets d'une société
company_projects:
    path: /companies/{companyId}/projects
    controller: App\Controller\ProjectController::listProjects
    methods: ['GET']

# Route pour afficher les détails d'un projet spécifique
project_details:
    path: /companies/{companyId}/projects/{projectId}
    controller: App\Controller\ProjectController::showProject
    methods: ['GET']

# Route pour modifier un projet
edit_project:
    path: /companies/{companyId}/projects/{projectId}/edit
    controller: App\Controller\ProjectController::editProject
    methods: ['GET', 'POST']

# Route pour supprimer un projet (remplacement de POST par DELETE pour la suppression)
delete_project:
    path: /companies/{companyId}/projects/{projectId}/delete
    controller: App\Controller\ProjectController::deleteProject
    methods: ['DELETE']


# Routes pour les utilisateurs
user_list:
    path: /users
    controller: App\Controller\UserController::listUsers
    methods: ['GET']

user_details:
    path: /user/{id}
    controller: App\Controller\UserController::getUserDetails
    methods: ['GET']

user_create:
    path: /users
    controller: App\Controller\UserController::createUser
    methods: ['POST']

user_edit:
    path: /user/{id}
    controller: App\Controller\UserController::editUser
    methods: ['PUT']

user_delete:
    path: /user/{id}
    controller: App\Controller\UserController::deleteUser
    methods: ['DELETE']

# Routes pour gérer les rôles des utilisateurs
user_view_roles:
    path: /user/{id}/roles
    controller: App\Controller\UserController::viewUserRoles
    methods: ['GET']

user_add_role:
    path: /user/{id}/roles
    controller: App\Controller\UserController::addRole
    methods: ['POST']

user_remove_role:
    path: /user/{id}/roles/{roleId}
    controller: App\Controller\UserController::removeRole
    methods: ['DELETE']
